language: go
go_import_path: forgerock.io/frconfigsrv
install: make get-deps
deploy:
  provider: releases
  api_key:
    secure: KwF8t6xiPSgZscvc5huXefv7DojhwPrDK3daRDRm81Aa1ImqT4zxIftoHvyzhs2GN9V2CIPxJlsLCrcIAodW7oiUJIqSIiI01LFKcWlVINhvW8bjsBPO9cfZquVvQYQp8RX+FfvUxJnpjcWGzVgNc/ku6uYGUjJNMJpAwUi47suVF5DOZNVrq8m2mAZrH8iu+iDMqZZoWpLLP58HceCfFKX6w5dDWKifae3dY6rSjCCelFXY3g8B76YqEqJSfz6Shs/Vtw0qA4YE84ILs6bRON+J41iYx5gpwOxD6JiqtGRqv+Ldcp9XhMDRnajD7FgNLMbydNKlHlteN56b7sJgE5woU4vZSkDP2BFl/OFGOpAfVaVMzTE66Hm4DwmsYcWTDRaxKosJ5J4FFg8GXHuFogyfwBezFALsU+s5GqGDy7csaFHmKCiKsIr8M6GaDGDMp4JhrCEEy7iCyNx+o8O69OrINzBozob+qigEiWzFnREFHBxMBn89vOxkS/JYzYQxBOaGm4YSBoYHcNikAraqHvUE31WSidyyy4wtD57pWkEpA9X7o0n+jg3R78txWp4/GBI5P07/Li7+BPJSCC0htY9bmMVOKxTEYXc8OVnrw5T70EpaW7whlFNQk9bkn8tt9pdLxIFnbxvZpQ7CfsRG675R3E2mSnaobIyIskcTrHM=
  file: build/frconfigsrv
  skip_cleanup: true
  on:
    repo: wstrange/frconfigsrv
